version: '3'

services:
  nginx:
    privileged: true
    restart: always
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    depends_on:
      - jenkins
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - 80:80

  registry:
    restart: always
    image: registry
    container_name: registry
    hostname: registry
    volumes:
      - ./registry:/var/lib/registry
    ports:
      - "5005:5005"
    environment:
      - REGISTRY_HTTP_ADDR=0.0.0.0:5005

  jenkins:
    restart: always
    image: jenkins/jenkins
    hostname: jenkins
    user: root
    ports:
      - 8080:8080
    environment:
      #- JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true -Dcasc.jenkins.config=/var/jenkins/home/casc_configs -Dorg.apache.commons.jelly.tags.fmt.timeZone=Europe/Moscow -Duser.timeZone=Europe/Moscow"
      - JAVA_OPTS="-Dhudson.model.DownloadService.noSignatureCheck=true"
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock